name = "tauri-update-server"
workers_dev = true
compatibility_date = "2022-07-26"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'meetmo'
GITHUB_REPO = 'grout-desktop-app'
GITHUB_TOKEN = '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' # Optional - used with private repos

[build]
command = "npm install && npm run build"
