name = "tauri-update-server"
workers_dev = true
compatibility_date = "2022-07-26"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'MeetMo'
GITHUB_REPO = 'grout-desktop-app'
GITHUB_TOKEN = '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' # Optional - used with private repos

[build]
command = "npm install && npm run build"
