name = "tauri-update-server"
workers_dev = true
compatibility_date = "2022-07-26"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'MeetMo'
GITHUB_REPO = 'grout-desktop-app'
GITHUB_TOKEN = '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' # Optional - used with private repos

[build]
command = "npm install && npm run build"
